import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import LanguageDetector from "i18next-browser-languagedetector";

// 22 languages. Keys are stable; values are short UI strings only.
type Dict = Record<string, string>;

const ar: Dict = {
  "app.name":"Giant","app.tagline":"دردشة مجتمعات وغرف ومحادثات خاصة",
  "auth.login":"تسجيل الدخول","auth.register":"إنشاء حساب","auth.username":"اسم المستخدم","auth.password":"كلمة المرور","auth.confirm":"تأكيد كلمة المرور",
  "auth.have_account":"لديك حساب؟","auth.no_account":"ليس لديك حساب؟","auth.loading":"جاري التحميل…","auth.logout":"تسجيل الخروج",
  "nav.rooms":"الغرف","nav.chats":"المحادثات","nav.profile":"حسابي","nav.settings":"الإعدادات","nav.friends":"الأصدقاء","nav.games":"الألعاب",
  "rooms.title":"غرف الدردشة","rooms.subtitle":"انضم لمجتمع أو ابدأ غرفتك","rooms.create":"إنشاء غرفة","rooms.create_title":"غرفة جديدة","rooms.name":"اسم الغرفة","rooms.description":"وصف الغرفة","rooms.empty":"لا توجد غرف بعد","rooms.members":"عضو","rooms.search":"ابحث عن غرفة…","rooms.no_results":"لا توجد نتائج",
  "room.placeholder":"اكتب رسالة…","room.send":"إرسال","room.leave":"الخروج من الغرفة","room.leave_confirm":"سيتم مسح رسائل الغرفة عند خروج آخر عضو","room.no_messages":"لا توجد رسائل بعد. كن أول من يكتب!","room.online":"متصل",
  "room.attach_image":"إرفاق صورة","room.record_voice":"تسجيل صوتي","room.recording":"جاري التسجيل…","room.stop":"إيقاف","room.image":"صورة","room.voice":"رسالة صوتية","room.uploading":"جاري الرفع…",
  "room.members_title":"الأعضاء","room.logs_title":"سجل الغرفة","room.kick":"طرد","room.ban":"حظر","room.unban":"إلغاء الحظر","room.promote":"ترقية لمشرف","room.demote":"إزالة الإشراف","room.transfer":"نقل الملكية","room.transfer_confirm":"هل تريد نقل ملكية الغرفة؟ لا يمكن التراجع.","room.owner":"المالك","room.admin":"مشرف","room.member":"عضو","room.banned":"محظور","room.action_done":"تم التنفيذ","room.banned_list":"المحظورون","room.no_bans":"لا يوجد محظورون","room.no_logs":"لا توجد أحداث بعد",
  "log.join":"انضم للغرفة","log.leave":"غادر الغرفة","log.kick":"تم طرده","log.ban":"تم حظره","log.unban":"تم رفع الحظر","log.promote":"تمت ترقيته","log.demote":"تم إزالة إشرافه","log.transfer":"أصبح المالك الجديد",
  "chats.title":"المحادثات","chats.subtitle":"محادثاتك الخاصة","chats.soon":"المحادثات الخاصة قريبًا","chats.empty":"لا توجد محادثات بعد",
  "profile.title":"حسابي","profile.bio":"النبذة التعريفية","profile.bio_placeholder":"اكتب نبذة عنك…","profile.save":"حفظ","profile.saved":"تم الحفظ","profile.avatar":"الصورة الشخصية","profile.change_photo":"تغيير الصورة","profile.username":"اسم المستخدم","profile.notifications":"الإشعارات","profile.account":"الحساب","profile.security":"الأمان","profile.about":"حول التطبيق",
  "friends.title":"الأصدقاء","friends.search":"ابحث باسم المستخدم…","friends.requests":"طلبات الصداقة","friends.my_friends":"أصدقائي","friends.add":"إضافة","friends.accept":"قبول","friends.reject":"رفض","friends.remove":"إزالة","friends.pending":"بانتظار الرد","friends.empty":"لا يوجد أصدقاء بعد","friends.no_users":"لا يوجد مستخدمون","friends.request_sent":"تم إرسال الطلب","friends.chat":"دردشة خاصة",
  "settings.title":"الإعدادات","settings.theme":"المظهر","settings.dark":"ليلي","settings.light":"فاتح","settings.language":"اللغة","settings.notifications":"الإشعارات","settings.notifications_on":"تفعيل الإشعارات",
  "game.title":"نادي الألعاب","game.subtitle":"خمن الرقم السري بين 1 و 100 — الفائز يربح 40 نقطة","game.join_seat":"انضمام للمقعد (10 نقاط)","game.charged":"تم خصم 10 نقاط للاشتراك","game.waitlisted":"تمت إضافتك لقائمة الانتظار","game.waiting_position":"موقعك في الانتظار","game.waitlist":"قائمة الانتظار","game.no_points":"رصيدك أقل من 10 نقاط","game.invalid_guess":"أدخل رقمًا بين 1 و 100","game.guess_placeholder":"خمن رقمًا 1-100","game.your_guess":"تخمينك","game.wait_others":"بانتظار باقي اللاعبين…","game.round":"الجولة","game.in_progress":"جارية","game.finished":"انتهت","game.time_left":"الوقت المتبقي","game.empty_seat":"مقعد فارغ","game.live_feed":"البث المباشر","game.rules":"4 لاعبين كحد أقصى — يبدأ الكمبيوتر حتى ينضم لاعبون حقيقيون.",
  "game.sys_round_started":"بدأت جولة جديدة. تم اختيار الرقم السري.","game.sys_user_joined":"انضم {{name}} إلى المقعد.","game.sys_user_guessed":"اللاعب {{name}} خمن الرقم {{value}}.","game.sys_winner":"🏆 الفائز {{name}}! الرقم السري كان {{secret}} وتخمينه {{guess}}. ربح 40 نقطة.","game.sys_replaced_ai":"تم استبدال لاعب الكمبيوتر بـ {{name}}.",
  "common.cancel":"إلغاء","common.error":"حدث خطأ","common.back":"رجوع","common.confirm":"تأكيد","common.search":"بحث","common.close":"إغلاق","common.send":"إرسال","common.loading":"جاري التحميل…",
  "notif.title":"الإشعارات","notif.empty":"لا توجد إشعارات","notif.unread":"غير مقروء","notif.from":"من","notif.mark_all":"تعليم الكل كمقروء","notif.new_message":"رسالة جديدة",
  "admin.title":"لوحة الإدارة","admin.subtitle":"أدوات المسؤول","admin.send_points":"إرسال نقاط","admin.target_user":"اسم المستخدم المستلم","admin.amount":"عدد النقاط","admin.points_sent":"تم إرسال النقاط","admin.broadcast":"إعلان عام","admin.broadcast_placeholder":"اكتب الإعلان الذي سيظهر للجميع…","admin.broadcast_sent":"تم إرسال الإعلان للجميع","admin.user_not_found":"المستخدم غير موجود","admin.only":"هذه الصفحة للمسؤولين فقط",
};
const en: Dict = {
  "app.name":"Giant","app.tagline":"Community chat rooms and private messages",
  "auth.login":"Log in","auth.register":"Sign up","auth.username":"Username","auth.password":"Password","auth.confirm":"Confirm password",
  "auth.have_account":"Have an account?","auth.no_account":"No account?","auth.loading":"Loading…","auth.logout":"Log out",
  "nav.rooms":"Rooms","nav.chats":"Chats","nav.profile":"Profile","nav.settings":"Settings","nav.friends":"Friends","nav.games":"Games",
  "rooms.title":"Chat rooms","rooms.subtitle":"Join a community or start your own","rooms.create":"New room","rooms.create_title":"New room","rooms.name":"Room name","rooms.description":"Description","rooms.empty":"No rooms yet","rooms.members":"members","rooms.search":"Search rooms…","rooms.no_results":"No results",
  "room.placeholder":"Type a message…","room.send":"Send","room.leave":"Leave room","room.leave_confirm":"Messages are erased when the last member leaves","room.no_messages":"No messages yet. Be the first!","room.online":"online",
  "room.attach_image":"Attach image","room.record_voice":"Record voice","room.recording":"Recording…","room.stop":"Stop","room.image":"Image","room.voice":"Voice message","room.uploading":"Uploading…",
  "room.members_title":"Members","room.logs_title":"Room log","room.kick":"Kick","room.ban":"Ban","room.unban":"Unban","room.promote":"Promote to admin","room.demote":"Remove admin","room.transfer":"Transfer ownership","room.transfer_confirm":"Transfer ownership? This cannot be undone.","room.owner":"Owner","room.admin":"Admin","room.member":"Member","room.banned":"Banned","room.action_done":"Done","room.banned_list":"Banned users","room.no_bans":"No banned users","room.no_logs":"No events yet",
  "log.join":"joined the room","log.leave":"left the room","log.kick":"was kicked","log.ban":"was banned","log.unban":"was unbanned","log.promote":"was promoted","log.demote":"was demoted","log.transfer":"became the new owner",
  "chats.title":"Chats","chats.subtitle":"Your private conversations","chats.soon":"Private chats coming soon","chats.empty":"No conversations yet",
  "profile.title":"Profile","profile.bio":"Bio","profile.bio_placeholder":"Write a short bio…","profile.save":"Save","profile.saved":"Saved","profile.avatar":"Avatar","profile.change_photo":"Change photo","profile.username":"Username","profile.notifications":"Notifications","profile.account":"Account","profile.security":"Security","profile.about":"About",
  "friends.title":"Friends","friends.search":"Search by username…","friends.requests":"Friend requests","friends.my_friends":"My friends","friends.add":"Add","friends.accept":"Accept","friends.reject":"Reject","friends.remove":"Remove","friends.pending":"Pending","friends.empty":"No friends yet","friends.no_users":"No users found","friends.request_sent":"Request sent","friends.chat":"Private chat",
  "settings.title":"Settings","settings.theme":"Theme","settings.dark":"Dark","settings.light":"Light","settings.language":"Language","settings.notifications":"Notifications","settings.notifications_on":"Enable notifications",
  "game.title":"Games Club","game.subtitle":"Guess the secret number 1-100 — winner gets 40 points","game.join_seat":"Take a seat (10 pts)","game.charged":"10 points charged","game.waitlisted":"Added to waitlist","game.waiting_position":"Waitlist position","game.waitlist":"Waitlist","game.no_points":"You need at least 10 points","game.invalid_guess":"Enter a number 1-100","game.guess_placeholder":"Guess 1-100","game.your_guess":"Your guess","game.wait_others":"Waiting for others…","game.round":"Round","game.in_progress":"In progress","game.finished":"Finished","game.time_left":"Time left","game.empty_seat":"Empty","game.live_feed":"Live feed","game.rules":"4 players max — bots play until real users join.",
  "game.sys_round_started":"New round started. Secret number picked.","game.sys_user_joined":"{{name}} took a seat.","game.sys_user_guessed":"{{name}} guessed {{value}}.","game.sys_winner":"🏆 Winner {{name}}! Secret was {{secret}}, guess {{guess}}. +40 points.","game.sys_replaced_ai":"Bot replaced by {{name}}.",
  "common.cancel":"Cancel","common.error":"Something went wrong","common.back":"Back","common.confirm":"Confirm","common.search":"Search","common.close":"Close",
};
const fr: Dict = {"app.name":"Giant","app.tagline":"Salons de discussion et messages privés","auth.login":"Connexion","auth.register":"S'inscrire","auth.username":"Nom d'utilisateur","auth.password":"Mot de passe","auth.confirm":"Confirmer le mot de passe","auth.have_account":"Vous avez un compte ?","auth.no_account":"Pas de compte ?","auth.loading":"Chargement…","auth.logout":"Déconnexion","nav.rooms":"Salons","nav.chats":"Messages","nav.profile":"Profil","nav.settings":"Paramètres","rooms.title":"Salons","rooms.subtitle":"Rejoignez une communauté ou créez la vôtre","rooms.create":"Nouveau salon","rooms.create_title":"Nouveau salon","rooms.name":"Nom du salon","rooms.description":"Description","rooms.empty":"Aucun salon","rooms.members":"membres","room.placeholder":"Écrire un message…","room.send":"Envoyer","room.leave":"Quitter","room.leave_confirm":"Les messages sont effacés quand le dernier membre part","room.no_messages":"Aucun message. Soyez le premier !","room.online":"en ligne","room.attach_image":"Joindre une image","room.record_voice":"Enregistrer","room.recording":"Enregistrement…","room.stop":"Arrêter","room.image":"Image","room.voice":"Message vocal","room.uploading":"Envoi…","chats.title":"Messages","chats.subtitle":"Vos conversations privées","chats.soon":"Messages privés bientôt","profile.title":"Profil","profile.bio":"Bio","profile.bio_placeholder":"Écrivez une courte bio…","profile.save":"Enregistrer","profile.saved":"Enregistré","profile.avatar":"Avatar","profile.change_photo":"Changer la photo","settings.title":"Paramètres","settings.theme":"Thème","settings.dark":"Sombre","settings.light":"Clair","settings.language":"Langue","common.cancel":"Annuler","common.error":"Une erreur s'est produite","common.back":"Retour"};
const es: Dict = {"app.name":"Giant","app.tagline":"Salas de chat y mensajes privados","auth.login":"Iniciar sesión","auth.register":"Registrarse","auth.username":"Usuario","auth.password":"Contraseña","auth.confirm":"Confirmar contraseña","auth.have_account":"¿Tienes cuenta?","auth.no_account":"¿Sin cuenta?","auth.loading":"Cargando…","auth.logout":"Salir","nav.rooms":"Salas","nav.chats":"Mensajes","nav.profile":"Perfil","nav.settings":"Ajustes","rooms.title":"Salas de chat","rooms.subtitle":"Únete a una comunidad","rooms.create":"Nueva sala","rooms.create_title":"Nueva sala","rooms.name":"Nombre","rooms.description":"Descripción","rooms.empty":"Sin salas","rooms.members":"miembros","room.placeholder":"Escribe un mensaje…","room.send":"Enviar","room.leave":"Salir","room.leave_confirm":"Los mensajes se borran cuando se va el último","room.no_messages":"Sin mensajes. ¡Sé el primero!","room.online":"en línea","room.attach_image":"Adjuntar imagen","room.record_voice":"Grabar voz","room.recording":"Grabando…","room.stop":"Detener","room.image":"Imagen","room.voice":"Mensaje de voz","room.uploading":"Subiendo…","chats.title":"Mensajes","chats.subtitle":"Tus chats privados","chats.soon":"Chats privados pronto","profile.title":"Perfil","profile.bio":"Biografía","profile.bio_placeholder":"Escribe una bio…","profile.save":"Guardar","profile.saved":"Guardado","profile.avatar":"Avatar","profile.change_photo":"Cambiar foto","settings.title":"Ajustes","settings.theme":"Tema","settings.dark":"Oscuro","settings.light":"Claro","settings.language":"Idioma","common.cancel":"Cancelar","common.error":"Ha ocurrido un error","common.back":"Atrás"};
const tr: Dict = {"app.name":"Giant","app.tagline":"Topluluk sohbet odaları ve özel mesajlar","auth.login":"Giriş","auth.register":"Kayıt ol","auth.username":"Kullanıcı adı","auth.password":"Şifre","auth.confirm":"Şifre tekrar","auth.have_account":"Hesabın var mı?","auth.no_account":"Hesap yok mu?","auth.loading":"Yükleniyor…","auth.logout":"Çıkış","nav.rooms":"Odalar","nav.chats":"Sohbetler","nav.profile":"Profil","nav.settings":"Ayarlar","rooms.title":"Sohbet odaları","rooms.subtitle":"Bir topluluğa katıl","rooms.create":"Yeni oda","rooms.create_title":"Yeni oda","rooms.name":"Oda adı","rooms.description":"Açıklama","rooms.empty":"Oda yok","rooms.members":"üye","room.placeholder":"Bir mesaj yaz…","room.send":"Gönder","room.leave":"Odadan çık","room.leave_confirm":"Son üye ayrılınca mesajlar silinir","room.no_messages":"Mesaj yok. İlk sen yaz!","room.online":"çevrimiçi","room.attach_image":"Resim ekle","room.record_voice":"Sesli kayıt","room.recording":"Kaydediliyor…","room.stop":"Dur","room.image":"Resim","room.voice":"Sesli mesaj","room.uploading":"Yükleniyor…","chats.title":"Sohbetler","chats.subtitle":"Özel sohbetlerin","chats.soon":"Özel sohbetler yakında","profile.title":"Profil","profile.bio":"Hakkında","profile.bio_placeholder":"Kısa bir tanıtım yaz…","profile.save":"Kaydet","profile.saved":"Kaydedildi","profile.avatar":"Avatar","profile.change_photo":"Fotoğrafı değiştir","settings.title":"Ayarlar","settings.theme":"Tema","settings.dark":"Koyu","settings.light":"Açık","settings.language":"Dil","common.cancel":"İptal","common.error":"Bir hata oluştu","common.back":"Geri"};
const ur: Dict = {"app.name":"Giant","app.tagline":"کمیونٹی چیٹ رومز اور پرائیویٹ پیغامات","auth.login":"لاگ ان","auth.register":"رجسٹر","auth.username":"یوزر نیم","auth.password":"پاس ورڈ","auth.confirm":"پاس ورڈ کی تصدیق","auth.have_account":"اکاؤنٹ ہے؟","auth.no_account":"اکاؤنٹ نہیں؟","auth.loading":"لوڈ ہو رہا ہے…","auth.logout":"لاگ آؤٹ","nav.rooms":"کمرے","nav.chats":"چیٹس","nav.profile":"پروفائل","nav.settings":"ترتیبات","rooms.title":"چیٹ رومز","rooms.subtitle":"کسی کمیونٹی میں شامل ہوں","rooms.create":"نیا کمرہ","rooms.create_title":"نیا کمرہ","rooms.name":"کمرے کا نام","rooms.description":"تفصیل","rooms.empty":"کوئی کمرہ نہیں","rooms.members":"اراکین","room.placeholder":"پیغام لکھیں…","room.send":"بھیجیں","room.leave":"کمرہ چھوڑیں","room.leave_confirm":"آخری رکن کے جانے پر پیغامات حذف ہو جائیں گے","room.no_messages":"کوئی پیغام نہیں۔ پہلا بنیں!","room.online":"آن لائن","room.attach_image":"تصویر منسلک کریں","room.record_voice":"آواز ریکارڈ کریں","room.recording":"ریکارڈنگ…","room.stop":"رکیں","room.image":"تصویر","room.voice":"صوتی پیغام","room.uploading":"اپلوڈ ہو رہا ہے…","chats.title":"چیٹس","chats.subtitle":"آپ کی نجی گفتگو","chats.soon":"نجی چیٹس جلد","profile.title":"پروفائل","profile.bio":"تعارف","profile.bio_placeholder":"مختصر تعارف لکھیں…","profile.save":"محفوظ کریں","profile.saved":"محفوظ ہو گیا","profile.avatar":"تصویر","profile.change_photo":"تصویر بدلیں","settings.title":"ترتیبات","settings.theme":"تھیم","settings.dark":"تاریک","settings.light":"روشن","settings.language":"زبان","common.cancel":"منسوخ","common.error":"خرابی پیش آئی","common.back":"واپس"};
const de: Dict = {"app.name":"Giant","app.tagline":"Community-Chats und private Nachrichten","auth.login":"Anmelden","auth.register":"Registrieren","auth.username":"Benutzername","auth.password":"Passwort","auth.confirm":"Passwort bestätigen","auth.have_account":"Schon ein Konto?","auth.no_account":"Kein Konto?","auth.loading":"Lädt…","auth.logout":"Abmelden","nav.rooms":"Räume","nav.chats":"Chats","nav.profile":"Profil","nav.settings":"Einstellungen","rooms.title":"Chaträume","rooms.subtitle":"Tritt einer Community bei","rooms.create":"Neuer Raum","rooms.create_title":"Neuer Raum","rooms.name":"Raumname","rooms.description":"Beschreibung","rooms.empty":"Keine Räume","rooms.members":"Mitglieder","room.placeholder":"Nachricht schreiben…","room.send":"Senden","room.leave":"Raum verlassen","room.leave_confirm":"Nachrichten werden gelöscht, sobald der letzte geht","room.no_messages":"Keine Nachrichten. Sei der Erste!","room.online":"online","room.attach_image":"Bild anhängen","room.record_voice":"Aufnehmen","room.recording":"Aufnahme…","room.stop":"Stopp","room.image":"Bild","room.voice":"Sprachnachricht","room.uploading":"Wird hochgeladen…","chats.title":"Chats","chats.subtitle":"Deine privaten Chats","chats.soon":"Private Chats bald","profile.title":"Profil","profile.bio":"Über mich","profile.bio_placeholder":"Kurze Bio…","profile.save":"Speichern","profile.saved":"Gespeichert","profile.avatar":"Avatar","profile.change_photo":"Foto ändern","settings.title":"Einstellungen","settings.theme":"Design","settings.dark":"Dunkel","settings.light":"Hell","settings.language":"Sprache","common.cancel":"Abbrechen","common.error":"Ein Fehler ist aufgetreten","common.back":"Zurück"};
const it: Dict = {"app.name":"Giant","app.tagline":"Stanze chat e messaggi privati","auth.login":"Accedi","auth.register":"Registrati","auth.username":"Nome utente","auth.password":"Password","auth.confirm":"Conferma password","auth.have_account":"Hai un account?","auth.no_account":"Nessun account?","auth.loading":"Caricamento…","auth.logout":"Esci","nav.rooms":"Stanze","nav.chats":"Chat","nav.profile":"Profilo","nav.settings":"Impostazioni","rooms.title":"Stanze","rooms.subtitle":"Unisciti a una community","rooms.create":"Nuova stanza","rooms.create_title":"Nuova stanza","rooms.name":"Nome","rooms.description":"Descrizione","rooms.empty":"Nessuna stanza","rooms.members":"membri","room.placeholder":"Scrivi…","room.send":"Invia","room.leave":"Esci","room.leave_confirm":"I messaggi si cancellano quando l'ultimo esce","room.no_messages":"Nessun messaggio. Inizia tu!","room.online":"online","room.attach_image":"Allega immagine","room.record_voice":"Registra","room.recording":"Registrazione…","room.stop":"Stop","room.image":"Immagine","room.voice":"Messaggio vocale","room.uploading":"Caricamento…","chats.title":"Chat","chats.subtitle":"Le tue chat private","chats.soon":"Chat private in arrivo","profile.title":"Profilo","profile.bio":"Bio","profile.bio_placeholder":"Scrivi una bio…","profile.save":"Salva","profile.saved":"Salvato","profile.avatar":"Avatar","profile.change_photo":"Cambia foto","settings.title":"Impostazioni","settings.theme":"Tema","settings.dark":"Scuro","settings.light":"Chiaro","settings.language":"Lingua","common.cancel":"Annulla","common.error":"Si è verificato un errore","common.back":"Indietro"};
const pt: Dict = {"app.name":"Giant","app.tagline":"Salas de bate-papo e mensagens privadas","auth.login":"Entrar","auth.register":"Cadastrar","auth.username":"Usuário","auth.password":"Senha","auth.confirm":"Confirmar senha","auth.have_account":"Tem conta?","auth.no_account":"Sem conta?","auth.loading":"Carregando…","auth.logout":"Sair","nav.rooms":"Salas","nav.chats":"Conversas","nav.profile":"Perfil","nav.settings":"Configurações","rooms.title":"Salas","rooms.subtitle":"Entre em uma comunidade","rooms.create":"Nova sala","rooms.create_title":"Nova sala","rooms.name":"Nome","rooms.description":"Descrição","rooms.empty":"Sem salas","rooms.members":"membros","room.placeholder":"Escreva uma mensagem…","room.send":"Enviar","room.leave":"Sair da sala","room.leave_confirm":"As mensagens são apagadas quando o último sai","room.no_messages":"Sem mensagens. Seja o primeiro!","room.online":"online","room.attach_image":"Anexar imagem","room.record_voice":"Gravar voz","room.recording":"Gravando…","room.stop":"Parar","room.image":"Imagem","room.voice":"Mensagem de voz","room.uploading":"Enviando…","chats.title":"Conversas","chats.subtitle":"Suas conversas privadas","chats.soon":"Conversas privadas em breve","profile.title":"Perfil","profile.bio":"Bio","profile.bio_placeholder":"Escreva uma bio…","profile.save":"Salvar","profile.saved":"Salvo","profile.avatar":"Avatar","profile.change_photo":"Mudar foto","settings.title":"Configurações","settings.theme":"Tema","settings.dark":"Escuro","settings.light":"Claro","settings.language":"Idioma","common.cancel":"Cancelar","common.error":"Ocorreu um erro","common.back":"Voltar"};
const ru: Dict = {"app.name":"Giant","app.tagline":"Чаты сообществ и личные сообщения","auth.login":"Войти","auth.register":"Регистрация","auth.username":"Имя пользователя","auth.password":"Пароль","auth.confirm":"Подтвердите пароль","auth.have_account":"Есть аккаунт?","auth.no_account":"Нет аккаунта?","auth.loading":"Загрузка…","auth.logout":"Выйти","nav.rooms":"Комнаты","nav.chats":"Чаты","nav.profile":"Профиль","nav.settings":"Настройки","rooms.title":"Комнаты","rooms.subtitle":"Присоединяйтесь к сообществу","rooms.create":"Новая комната","rooms.create_title":"Новая комната","rooms.name":"Название","rooms.description":"Описание","rooms.empty":"Нет комнат","rooms.members":"участников","room.placeholder":"Напишите сообщение…","room.send":"Отправить","room.leave":"Выйти","room.leave_confirm":"Сообщения удаляются, когда уходит последний","room.no_messages":"Сообщений нет. Будьте первым!","room.online":"в сети","room.attach_image":"Прикрепить фото","room.record_voice":"Записать голос","room.recording":"Запись…","room.stop":"Стоп","room.image":"Фото","room.voice":"Голосовое","room.uploading":"Загрузка…","chats.title":"Чаты","chats.subtitle":"Личные чаты","chats.soon":"Личные чаты скоро","profile.title":"Профиль","profile.bio":"О себе","profile.bio_placeholder":"Расскажите о себе…","profile.save":"Сохранить","profile.saved":"Сохранено","profile.avatar":"Аватар","profile.change_photo":"Изменить фото","settings.title":"Настройки","settings.theme":"Тема","settings.dark":"Тёмная","settings.light":"Светлая","settings.language":"Язык","common.cancel":"Отмена","common.error":"Произошла ошибка","common.back":"Назад"};
const zh: Dict = {"app.name":"Giant","app.tagline":"社区聊天室与私聊","auth.login":"登录","auth.register":"注册","auth.username":"用户名","auth.password":"密码","auth.confirm":"确认密码","auth.have_account":"已有账号？","auth.no_account":"没有账号？","auth.loading":"加载中…","auth.logout":"退出","nav.rooms":"房间","nav.chats":"私聊","nav.profile":"我的","nav.settings":"设置","rooms.title":"聊天室","rooms.subtitle":"加入社区","rooms.create":"新建房间","rooms.create_title":"新建房间","rooms.name":"房间名","rooms.description":"描述","rooms.empty":"暂无房间","rooms.members":"成员","room.placeholder":"输入消息…","room.send":"发送","room.leave":"离开房间","room.leave_confirm":"最后一人离开时消息将被清空","room.no_messages":"暂无消息，发第一条吧！","room.online":"在线","room.attach_image":"图片","room.record_voice":"录音","room.recording":"录音中…","room.stop":"停止","room.image":"图片","room.voice":"语音","room.uploading":"上传中…","chats.title":"私聊","chats.subtitle":"你的私聊","chats.soon":"私聊即将上线","profile.title":"我的","profile.bio":"简介","profile.bio_placeholder":"写点什么…","profile.save":"保存","profile.saved":"已保存","profile.avatar":"头像","profile.change_photo":"更换头像","settings.title":"设置","settings.theme":"主题","settings.dark":"深色","settings.light":"浅色","settings.language":"语言","common.cancel":"取消","common.error":"出错了","common.back":"返回"};
const ja: Dict = {"app.name":"Giant","app.tagline":"コミュニティチャットとプライベートメッセージ","auth.login":"ログイン","auth.register":"新規登録","auth.username":"ユーザー名","auth.password":"パスワード","auth.confirm":"パスワード確認","auth.have_account":"アカウントあり？","auth.no_account":"アカウントなし？","auth.loading":"読み込み中…","auth.logout":"ログアウト","nav.rooms":"ルーム","nav.chats":"チャット","nav.profile":"プロフィール","nav.settings":"設定","rooms.title":"チャットルーム","rooms.subtitle":"コミュニティに参加","rooms.create":"新規ルーム","rooms.create_title":"新規ルーム","rooms.name":"名前","rooms.description":"説明","rooms.empty":"ルームなし","rooms.members":"人","room.placeholder":"メッセージを入力…","room.send":"送信","room.leave":"退出","room.leave_confirm":"最後の人が退出するとメッセージは削除されます","room.no_messages":"メッセージなし。最初に投稿しよう！","room.online":"オンライン","room.attach_image":"画像","room.record_voice":"録音","room.recording":"録音中…","room.stop":"停止","room.image":"画像","room.voice":"ボイスメッセージ","room.uploading":"アップロード中…","chats.title":"チャット","chats.subtitle":"プライベートチャット","chats.soon":"プライベートチャットは近日公開","profile.title":"プロフィール","profile.bio":"自己紹介","profile.bio_placeholder":"自己紹介を書く…","profile.save":"保存","profile.saved":"保存しました","profile.avatar":"アバター","profile.change_photo":"写真を変更","settings.title":"設定","settings.theme":"テーマ","settings.dark":"ダーク","settings.light":"ライト","settings.language":"言語","common.cancel":"キャンセル","common.error":"エラーが発生しました","common.back":"戻る"};
const ko: Dict = {"app.name":"Giant","app.tagline":"커뮤니티 채팅과 개인 메시지","auth.login":"로그인","auth.register":"가입","auth.username":"사용자명","auth.password":"비밀번호","auth.confirm":"비밀번호 확인","auth.have_account":"계정이 있나요?","auth.no_account":"계정이 없나요?","auth.loading":"로딩 중…","auth.logout":"로그아웃","nav.rooms":"방","nav.chats":"채팅","nav.profile":"프로필","nav.settings":"설정","rooms.title":"채팅방","rooms.subtitle":"커뮤니티 참여","rooms.create":"새 방","rooms.create_title":"새 방","rooms.name":"이름","rooms.description":"설명","rooms.empty":"방 없음","rooms.members":"명","room.placeholder":"메시지 입력…","room.send":"보내기","room.leave":"방 나가기","room.leave_confirm":"마지막 멤버가 나가면 메시지가 삭제됩니다","room.no_messages":"메시지가 없습니다. 첫 메시지를 보내세요!","room.online":"온라인","room.attach_image":"이미지","room.record_voice":"녹음","room.recording":"녹음 중…","room.stop":"중지","room.image":"이미지","room.voice":"음성 메시지","room.uploading":"업로드 중…","chats.title":"채팅","chats.subtitle":"개인 채팅","chats.soon":"개인 채팅 곧 출시","profile.title":"프로필","profile.bio":"소개","profile.bio_placeholder":"간단한 소개…","profile.save":"저장","profile.saved":"저장됨","profile.avatar":"아바타","profile.change_photo":"사진 변경","settings.title":"설정","settings.theme":"테마","settings.dark":"다크","settings.light":"라이트","settings.language":"언어","common.cancel":"취소","common.error":"오류가 발생했습니다","common.back":"뒤로"};
const hi: Dict = {"app.name":"Giant","app.tagline":"समुदाय चैट और निजी संदेश","auth.login":"लॉगिन","auth.register":"साइन अप","auth.username":"उपयोगकर्ता नाम","auth.password":"पासवर्ड","auth.confirm":"पासवर्ड पुष्टि","auth.have_account":"खाता है?","auth.no_account":"खाता नहीं?","auth.loading":"लोड हो रहा है…","auth.logout":"लॉगआउट","nav.rooms":"कक्ष","nav.chats":"चैट","nav.profile":"प्रोफ़ाइल","nav.settings":"सेटिंग","rooms.title":"चैट कक्ष","rooms.subtitle":"समुदाय में शामिल हों","rooms.create":"नया कक्ष","rooms.create_title":"नया कक्ष","rooms.name":"नाम","rooms.description":"विवरण","rooms.empty":"कोई कक्ष नहीं","rooms.members":"सदस्य","room.placeholder":"संदेश लिखें…","room.send":"भेजें","room.leave":"कक्ष छोड़ें","room.leave_confirm":"अंतिम सदस्य के जाने पर संदेश हटा दिए जाते हैं","room.no_messages":"कोई संदेश नहीं। पहले बनें!","room.online":"ऑनलाइन","room.attach_image":"छवि","room.record_voice":"रिकॉर्ड","room.recording":"रिकॉर्डिंग…","room.stop":"रोकें","room.image":"छवि","room.voice":"वॉयस संदेश","room.uploading":"अपलोड हो रहा है…","chats.title":"चैट","chats.subtitle":"आपकी निजी चैट","chats.soon":"निजी चैट जल्द","profile.title":"प्रोफ़ाइल","profile.bio":"बायो","profile.bio_placeholder":"बायो लिखें…","profile.save":"सहेजें","profile.saved":"सहेजा गया","profile.avatar":"अवतार","profile.change_photo":"फ़ोटो बदलें","settings.title":"सेटिंग","settings.theme":"थीम","settings.dark":"डार्क","settings.light":"लाइट","settings.language":"भाषा","common.cancel":"रद्द","common.error":"त्रुटि हुई","common.back":"वापस"};
const id: Dict = {"app.name":"Giant","app.tagline":"Ruang obrolan komunitas dan pesan pribadi","auth.login":"Masuk","auth.register":"Daftar","auth.username":"Nama pengguna","auth.password":"Kata sandi","auth.confirm":"Konfirmasi kata sandi","auth.have_account":"Punya akun?","auth.no_account":"Belum punya?","auth.loading":"Memuat…","auth.logout":"Keluar","nav.rooms":"Ruang","nav.chats":"Chat","nav.profile":"Profil","nav.settings":"Pengaturan","rooms.title":"Ruang obrolan","rooms.subtitle":"Gabung komunitas","rooms.create":"Ruang baru","rooms.create_title":"Ruang baru","rooms.name":"Nama","rooms.description":"Deskripsi","rooms.empty":"Belum ada","rooms.members":"anggota","room.placeholder":"Tulis pesan…","room.send":"Kirim","room.leave":"Keluar","room.leave_confirm":"Pesan dihapus saat anggota terakhir keluar","room.no_messages":"Belum ada pesan. Jadilah yang pertama!","room.online":"online","room.attach_image":"Lampirkan gambar","room.record_voice":"Rekam suara","room.recording":"Merekam…","room.stop":"Berhenti","room.image":"Gambar","room.voice":"Pesan suara","room.uploading":"Mengunggah…","chats.title":"Chat","chats.subtitle":"Chat pribadi","chats.soon":"Chat pribadi segera","profile.title":"Profil","profile.bio":"Bio","profile.bio_placeholder":"Tulis bio…","profile.save":"Simpan","profile.saved":"Tersimpan","profile.avatar":"Avatar","profile.change_photo":"Ganti foto","settings.title":"Pengaturan","settings.theme":"Tema","settings.dark":"Gelap","settings.light":"Terang","settings.language":"Bahasa","common.cancel":"Batal","common.error":"Terjadi kesalahan","common.back":"Kembali"};
const fa: Dict = {"app.name":"Giant","app.tagline":"اتاق‌های گفتگو و پیام‌های خصوصی","auth.login":"ورود","auth.register":"ثبت‌نام","auth.username":"نام کاربری","auth.password":"رمز عبور","auth.confirm":"تأیید رمز","auth.have_account":"حساب دارید؟","auth.no_account":"حساب ندارید؟","auth.loading":"در حال بارگذاری…","auth.logout":"خروج","nav.rooms":"اتاق‌ها","nav.chats":"چت‌ها","nav.profile":"پروفایل","nav.settings":"تنظیمات","rooms.title":"اتاق‌های گفتگو","rooms.subtitle":"به یک جامعه بپیوندید","rooms.create":"اتاق جدید","rooms.create_title":"اتاق جدید","rooms.name":"نام","rooms.description":"توضیحات","rooms.empty":"اتاقی نیست","rooms.members":"عضو","room.placeholder":"پیام بنویسید…","room.send":"ارسال","room.leave":"خروج از اتاق","room.leave_confirm":"با خروج آخرین عضو پیام‌ها پاک می‌شوند","room.no_messages":"پیامی نیست. اولین باشید!","room.online":"آنلاین","room.attach_image":"تصویر","room.record_voice":"ضبط صدا","room.recording":"در حال ضبط…","room.stop":"توقف","room.image":"تصویر","room.voice":"پیام صوتی","room.uploading":"در حال بارگذاری…","chats.title":"چت‌ها","chats.subtitle":"چت‌های خصوصی","chats.soon":"چت خصوصی به‌زودی","profile.title":"پروفایل","profile.bio":"بیو","profile.bio_placeholder":"کمی درباره خود بنویسید…","profile.save":"ذخیره","profile.saved":"ذخیره شد","profile.avatar":"آواتار","profile.change_photo":"تغییر عکس","settings.title":"تنظیمات","settings.theme":"تم","settings.dark":"تاریک","settings.light":"روشن","settings.language":"زبان","common.cancel":"لغو","common.error":"خطایی رخ داد","common.back":"بازگشت"};
const nl: Dict = {"app.name":"Giant","app.tagline":"Community-chats en privéberichten","auth.login":"Inloggen","auth.register":"Aanmelden","auth.username":"Gebruikersnaam","auth.password":"Wachtwoord","auth.confirm":"Bevestig wachtwoord","auth.have_account":"Heb je een account?","auth.no_account":"Geen account?","auth.loading":"Laden…","auth.logout":"Uitloggen","nav.rooms":"Kamers","nav.chats":"Chats","nav.profile":"Profiel","nav.settings":"Instellingen","rooms.title":"Chatkamers","rooms.subtitle":"Word lid van een community","rooms.create":"Nieuwe kamer","rooms.create_title":"Nieuwe kamer","rooms.name":"Naam","rooms.description":"Beschrijving","rooms.empty":"Geen kamers","rooms.members":"leden","room.placeholder":"Typ een bericht…","room.send":"Verstuur","room.leave":"Verlaat kamer","room.leave_confirm":"Berichten worden gewist als de laatste vertrekt","room.no_messages":"Nog geen berichten. Wees de eerste!","room.online":"online","room.attach_image":"Afbeelding","room.record_voice":"Opname","room.recording":"Opnemen…","room.stop":"Stop","room.image":"Afbeelding","room.voice":"Spraakbericht","room.uploading":"Uploaden…","chats.title":"Chats","chats.subtitle":"Je privéchats","chats.soon":"Privéchats binnenkort","profile.title":"Profiel","profile.bio":"Bio","profile.bio_placeholder":"Schrijf een korte bio…","profile.save":"Opslaan","profile.saved":"Opgeslagen","profile.avatar":"Avatar","profile.change_photo":"Foto wijzigen","settings.title":"Instellingen","settings.theme":"Thema","settings.dark":"Donker","settings.light":"Licht","settings.language":"Taal","common.cancel":"Annuleren","common.error":"Er is een fout opgetreden","common.back":"Terug"};
const pl: Dict = {"app.name":"Giant","app.tagline":"Pokoje społecznościowe i wiadomości prywatne","auth.login":"Zaloguj","auth.register":"Zarejestruj","auth.username":"Nazwa","auth.password":"Hasło","auth.confirm":"Potwierdź hasło","auth.have_account":"Masz konto?","auth.no_account":"Nie masz konta?","auth.loading":"Ładowanie…","auth.logout":"Wyloguj","nav.rooms":"Pokoje","nav.chats":"Czaty","nav.profile":"Profil","nav.settings":"Ustawienia","rooms.title":"Pokoje","rooms.subtitle":"Dołącz do społeczności","rooms.create":"Nowy pokój","rooms.create_title":"Nowy pokój","rooms.name":"Nazwa","rooms.description":"Opis","rooms.empty":"Brak pokoi","rooms.members":"członków","room.placeholder":"Napisz wiadomość…","room.send":"Wyślij","room.leave":"Opuść","room.leave_confirm":"Wiadomości są kasowane, gdy odejdzie ostatni","room.no_messages":"Brak wiadomości. Bądź pierwszy!","room.online":"online","room.attach_image":"Załącz obraz","room.record_voice":"Nagraj","room.recording":"Nagrywanie…","room.stop":"Stop","room.image":"Obraz","room.voice":"Głosowa","room.uploading":"Wysyłanie…","chats.title":"Czaty","chats.subtitle":"Twoje prywatne czaty","chats.soon":"Prywatne czaty wkrótce","profile.title":"Profil","profile.bio":"Bio","profile.bio_placeholder":"Napisz krótkie bio…","profile.save":"Zapisz","profile.saved":"Zapisano","profile.avatar":"Awatar","profile.change_photo":"Zmień zdjęcie","settings.title":"Ustawienia","settings.theme":"Motyw","settings.dark":"Ciemny","settings.light":"Jasny","settings.language":"Język","common.cancel":"Anuluj","common.error":"Wystąpił błąd","common.back":"Wstecz"};
const sv: Dict = {"app.name":"Giant","app.tagline":"Community-chattar och privata meddelanden","auth.login":"Logga in","auth.register":"Registrera","auth.username":"Användarnamn","auth.password":"Lösenord","auth.confirm":"Bekräfta lösenord","auth.have_account":"Har konto?","auth.no_account":"Inget konto?","auth.loading":"Laddar…","auth.logout":"Logga ut","nav.rooms":"Rum","nav.chats":"Chattar","nav.profile":"Profil","nav.settings":"Inställningar","rooms.title":"Chattrum","rooms.subtitle":"Gå med i en community","rooms.create":"Nytt rum","rooms.create_title":"Nytt rum","rooms.name":"Namn","rooms.description":"Beskrivning","rooms.empty":"Inga rum","rooms.members":"medlemmar","room.placeholder":"Skriv ett meddelande…","room.send":"Skicka","room.leave":"Lämna","room.leave_confirm":"Meddelanden raderas när sista går","room.no_messages":"Inga meddelanden. Var först!","room.online":"online","room.attach_image":"Bifoga bild","room.record_voice":"Spela in","room.recording":"Spelar in…","room.stop":"Stopp","room.image":"Bild","room.voice":"Röstmeddelande","room.uploading":"Laddar upp…","chats.title":"Chattar","chats.subtitle":"Dina privata chattar","chats.soon":"Privata chattar snart","profile.title":"Profil","profile.bio":"Bio","profile.bio_placeholder":"Skriv en kort bio…","profile.save":"Spara","profile.saved":"Sparat","profile.avatar":"Avatar","profile.change_photo":"Byt bild","settings.title":"Inställningar","settings.theme":"Tema","settings.dark":"Mörkt","settings.light":"Ljust","settings.language":"Språk","common.cancel":"Avbryt","common.error":"Något gick fel","common.back":"Tillbaka"};
const vi: Dict = {"app.name":"Giant","app.tagline":"Phòng chat cộng đồng và tin nhắn riêng","auth.login":"Đăng nhập","auth.register":"Đăng ký","auth.username":"Tên đăng nhập","auth.password":"Mật khẩu","auth.confirm":"Xác nhận mật khẩu","auth.have_account":"Đã có tài khoản?","auth.no_account":"Chưa có?","auth.loading":"Đang tải…","auth.logout":"Đăng xuất","nav.rooms":"Phòng","nav.chats":"Tin nhắn","nav.profile":"Hồ sơ","nav.settings":"Cài đặt","rooms.title":"Phòng chat","rooms.subtitle":"Tham gia cộng đồng","rooms.create":"Phòng mới","rooms.create_title":"Phòng mới","rooms.name":"Tên","rooms.description":"Mô tả","rooms.empty":"Chưa có phòng","rooms.members":"thành viên","room.placeholder":"Nhập tin nhắn…","room.send":"Gửi","room.leave":"Rời phòng","room.leave_confirm":"Tin nhắn bị xoá khi người cuối cùng rời","room.no_messages":"Chưa có tin nhắn. Bạn là người đầu!","room.online":"trực tuyến","room.attach_image":"Đính kèm ảnh","room.record_voice":"Ghi âm","room.recording":"Đang ghi…","room.stop":"Dừng","room.image":"Ảnh","room.voice":"Tin nhắn thoại","room.uploading":"Đang tải lên…","chats.title":"Tin nhắn","chats.subtitle":"Tin nhắn riêng","chats.soon":"Tin nhắn riêng sắp ra mắt","profile.title":"Hồ sơ","profile.bio":"Tiểu sử","profile.bio_placeholder":"Viết vài dòng…","profile.save":"Lưu","profile.saved":"Đã lưu","profile.avatar":"Ảnh đại diện","profile.change_photo":"Đổi ảnh","settings.title":"Cài đặt","settings.theme":"Giao diện","settings.dark":"Tối","settings.light":"Sáng","settings.language":"Ngôn ngữ","common.cancel":"Huỷ","common.error":"Đã xảy ra lỗi","common.back":"Quay lại"};
const th: Dict = {"app.name":"Giant","app.tagline":"ห้องแชทชุมชนและข้อความส่วนตัว","auth.login":"เข้าสู่ระบบ","auth.register":"สมัคร","auth.username":"ชื่อผู้ใช้","auth.password":"รหัสผ่าน","auth.confirm":"ยืนยันรหัสผ่าน","auth.have_account":"มีบัญชีแล้ว?","auth.no_account":"ยังไม่มีบัญชี?","auth.loading":"กำลังโหลด…","auth.logout":"ออกจากระบบ","nav.rooms":"ห้อง","nav.chats":"แชท","nav.profile":"โปรไฟล์","nav.settings":"ตั้งค่า","rooms.title":"ห้องแชท","rooms.subtitle":"เข้าร่วมชุมชน","rooms.create":"ห้องใหม่","rooms.create_title":"ห้องใหม่","rooms.name":"ชื่อ","rooms.description":"คำอธิบาย","rooms.empty":"ไม่มีห้อง","rooms.members":"สมาชิก","room.placeholder":"พิมพ์ข้อความ…","room.send":"ส่ง","room.leave":"ออกจากห้อง","room.leave_confirm":"ข้อความจะถูกลบเมื่อคนสุดท้ายออก","room.no_messages":"ยังไม่มีข้อความ เริ่มแรกเลย!","room.online":"ออนไลน์","room.attach_image":"แนบรูป","room.record_voice":"บันทึกเสียง","room.recording":"กำลังบันทึก…","room.stop":"หยุด","room.image":"รูป","room.voice":"ข้อความเสียง","room.uploading":"กำลังอัปโหลด…","chats.title":"แชท","chats.subtitle":"แชทส่วนตัวของคุณ","chats.soon":"แชทส่วนตัวเร็วๆ นี้","profile.title":"โปรไฟล์","profile.bio":"ประวัติ","profile.bio_placeholder":"เขียนประวัติสั้นๆ…","profile.save":"บันทึก","profile.saved":"บันทึกแล้ว","profile.avatar":"อวตาร","profile.change_photo":"เปลี่ยนรูป","settings.title":"ตั้งค่า","settings.theme":"ธีม","settings.dark":"มืด","settings.light":"สว่าง","settings.language":"ภาษา","common.cancel":"ยกเลิก","common.error":"เกิดข้อผิดพลาด","common.back":"กลับ"};
const he: Dict = {"app.name":"Giant","app.tagline":"חדרי צ'אט קהילתיים והודעות פרטיות","auth.login":"כניסה","auth.register":"הרשמה","auth.username":"שם משתמש","auth.password":"סיסמה","auth.confirm":"אימות סיסמה","auth.have_account":"יש חשבון?","auth.no_account":"אין חשבון?","auth.loading":"טוען…","auth.logout":"התנתק","nav.rooms":"חדרים","nav.chats":"צ'אטים","nav.profile":"פרופיל","nav.settings":"הגדרות","rooms.title":"חדרי צ'אט","rooms.subtitle":"הצטרף לקהילה","rooms.create":"חדר חדש","rooms.create_title":"חדר חדש","rooms.name":"שם","rooms.description":"תיאור","rooms.empty":"אין חדרים","rooms.members":"חברים","room.placeholder":"כתוב הודעה…","room.send":"שלח","room.leave":"צא מהחדר","room.leave_confirm":"ההודעות נמחקות כשהאחרון יוצא","room.no_messages":"אין הודעות. היה הראשון!","room.online":"מחובר","room.attach_image":"צרף תמונה","room.record_voice":"הקלט קול","room.recording":"מקליט…","room.stop":"עצור","room.image":"תמונה","room.voice":"הודעה קולית","room.uploading":"מעלה…","chats.title":"צ'אטים","chats.subtitle":"הצ'אטים הפרטיים שלך","chats.soon":"צ'אטים פרטיים בקרוב","profile.title":"פרופיל","profile.bio":"ביו","profile.bio_placeholder":"כתוב ביו קצר…","profile.save":"שמור","profile.saved":"נשמר","profile.avatar":"אווטאר","profile.change_photo":"החלף תמונה","settings.title":"הגדרות","settings.theme":"ערכת נושא","settings.dark":"כהה","settings.light":"בהיר","settings.language":"שפה","common.cancel":"ביטול","common.error":"אירעה שגיאה","common.back":"חזרה"};
const ms: Dict = {"app.name":"Giant","app.tagline":"Bilik sembang komuniti dan mesej peribadi","auth.login":"Log masuk","auth.register":"Daftar","auth.username":"Nama pengguna","auth.password":"Kata laluan","auth.confirm":"Sahkan kata laluan","auth.have_account":"Ada akaun?","auth.no_account":"Tiada akaun?","auth.loading":"Memuatkan…","auth.logout":"Log keluar","nav.rooms":"Bilik","nav.chats":"Sembang","nav.profile":"Profil","nav.settings":"Tetapan","rooms.title":"Bilik sembang","rooms.subtitle":"Sertai komuniti","rooms.create":"Bilik baharu","rooms.create_title":"Bilik baharu","rooms.name":"Nama","rooms.description":"Penerangan","rooms.empty":"Tiada bilik","rooms.members":"ahli","room.placeholder":"Taip mesej…","room.send":"Hantar","room.leave":"Tinggalkan","room.leave_confirm":"Mesej dipadam apabila ahli terakhir pergi","room.no_messages":"Tiada mesej. Jadilah yang pertama!","room.online":"dalam talian","room.attach_image":"Lampirkan imej","room.record_voice":"Rakam suara","room.recording":"Merakam…","room.stop":"Henti","room.image":"Imej","room.voice":"Mesej suara","room.uploading":"Memuat naik…","chats.title":"Sembang","chats.subtitle":"Sembang peribadi","chats.soon":"Sembang peribadi tidak lama lagi","profile.title":"Profil","profile.bio":"Bio","profile.bio_placeholder":"Tulis bio ringkas…","profile.save":"Simpan","profile.saved":"Disimpan","profile.avatar":"Avatar","profile.change_photo":"Tukar foto","settings.title":"Tetapan","settings.theme":"Tema","settings.dark":"Gelap","settings.light":"Cerah","settings.language":"Bahasa","common.cancel":"Batal","common.error":"Berlaku ralat","common.back":"Kembali"};

export const SUPPORTED_LANGUAGES = [
  { code: "ar", name: "العربية", dir: "rtl" },
  { code: "en", name: "English", dir: "ltr" },
  { code: "fr", name: "Français", dir: "ltr" },
  { code: "es", name: "Español", dir: "ltr" },
  { code: "de", name: "Deutsch", dir: "ltr" },
  { code: "it", name: "Italiano", dir: "ltr" },
  { code: "pt", name: "Português", dir: "ltr" },
  { code: "ru", name: "Русский", dir: "ltr" },
  { code: "tr", name: "Türkçe", dir: "ltr" },
  { code: "fa", name: "فارسی", dir: "rtl" },
  { code: "ur", name: "اردو", dir: "rtl" },
  { code: "he", name: "עברית", dir: "rtl" },
  { code: "hi", name: "हिन्दी", dir: "ltr" },
  { code: "zh", name: "中文", dir: "ltr" },
  { code: "ja", name: "日本語", dir: "ltr" },
  { code: "ko", name: "한국어", dir: "ltr" },
  { code: "id", name: "Indonesia", dir: "ltr" },
  { code: "ms", name: "Melayu", dir: "ltr" },
  { code: "vi", name: "Tiếng Việt", dir: "ltr" },
  { code: "th", name: "ไทย", dir: "ltr" },
  { code: "nl", name: "Nederlands", dir: "ltr" },
  { code: "pl", name: "Polski", dir: "ltr" },
  { code: "sv", name: "Svenska", dir: "ltr" },
] as const;

const resources = {
  ar:{translation:ar}, en:{translation:en}, fr:{translation:fr}, es:{translation:es},
  de:{translation:de}, it:{translation:it}, pt:{translation:pt}, ru:{translation:ru},
  tr:{translation:tr}, fa:{translation:fa}, ur:{translation:ur}, he:{translation:he},
  hi:{translation:hi}, zh:{translation:zh}, ja:{translation:ja}, ko:{translation:ko},
  id:{translation:id}, ms:{translation:ms}, vi:{translation:vi}, th:{translation:th},
  nl:{translation:nl}, pl:{translation:pl}, sv:{translation:sv},
};

if (!i18n.isInitialized) {
  i18n.use(LanguageDetector).use(initReactI18next).init({
    resources,
    fallbackLng: ["en", "ar"],
    supportedLngs: SUPPORTED_LANGUAGES.map((l) => l.code),
    interpolation: { escapeValue: false },
    detection: { order: ["localStorage", "navigator"], caches: ["localStorage"], lookupLocalStorage: "giant.lang" },
  });
}

export function applyLanguageDir(code: string) {
  const lang = SUPPORTED_LANGUAGES.find((l) => l.code === code) ?? SUPPORTED_LANGUAGES[0];
  if (typeof document !== "undefined") {
    document.documentElement.lang = lang.code;
    document.documentElement.dir = lang.dir;
  }
}

export default i18n;
