/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/site'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SiteRegisterRouteImport } from './routes/site/register'
import { Route as SiteLoginRouteImport } from './routes/site/login'
import { Route as SiteAccountRouteImport } from './routes/site/account'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as AppStoriesRouteImport } from './routes/app/stories'
import { Route as AppStoreRouteImport } from './routes/app/store'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppMy_profileRouteImport } from './routes/app/my_profile'
import { Route as AppGamesRouteImport } from './routes/app/games'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppDailyTasksRouteImport } from './routes/app/daily-tasks'
import { Route as AppCreateRoomRouteImport } from './routes/app/create-room'
import { Route as AppCommunityRouteImport } from './routes/app/community'
import { Route as AppCallsRouteImport } from './routes/app/calls'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppActivityRouteImport } from './routes/app/activity'
import { Route as AppAchievementsRouteImport } from './routes/app/achievements'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as AppChatsIndexRouteImport } from './routes/app/chats.index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin.index'
import { Route as AppRoomsIdRouteImport } from './routes/app/rooms.$id'
import { Route as AppProfileIdRouteImport } from './routes/app/profile.$id'
import { Route as AppChatsIdRouteImport } from './routes/app/chats.$id'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin.users'
import { Route as AppAdminUpdatesRouteImport } from './routes/app/admin.updates'
import { Route as AppAdminStoriesRouteImport } from './routes/app/admin.stories'
import { Route as AppAdminRoomsRouteImport } from './routes/app/admin.rooms'
import { Route as AppAdminCommunityRouteImport } from './routes/app/admin.community'
import { Route as ApiPublicSearchTrackRouteImport } from './routes/api/public/search-track'
import { Route as ApiPublicOtaPublishRouteImport } from './routes/api/public/ota-publish'
import { Route as ApiPublicGiantBotWebhookRouteImport } from './routes/api/public/giant-bot-webhook'
import { Route as AppRoomsIdInvitesRouteImport } from './routes/app/rooms.$id.invites'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteRegisterRoute = SiteRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeaturesRoute,
} as any)
const AppStoriesRoute = AppStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMy_profileRoute = AppMy_profileRouteImport.update({
  id: '/my_profile',
  path: '/my_profile',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppDailyTasksRoute = AppDailyTasksRouteImport.update({
  id: '/daily-tasks',
  path: '/daily-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoomRoute = AppCreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppRoomsIdRoute = AppRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIdRoute = AppChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUpdatesRoute = AppAdminUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStoriesRoute = AppAdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRoomsRoute = AppAdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminCommunityRoute = AppAdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicSearchTrackRoute = ApiPublicSearchTrackRouteImport.update({
  id: '/api/public/search-track',
  path: '/api/public/search-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOtaPublishRoute = ApiPublicOtaPublishRouteImport.update({
  id: '/api/public/ota-publish',
  path: '/api/public/ota-publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGiantBotWebhookRoute =
  ApiPublicGiantBotWebhookRouteImport.update({
    id: '/api/public/giant-bot-webhook',
    path: '/api/public/giant-bot-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppRoomsIdInvitesRoute = AppRoomsIdInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppRoomsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRouteWithChildren
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/app/account': typeof AppAccountRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/calls': typeof AppCallsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create-room': typeof AppCreateRoomRoute
  '/app/daily-tasks': typeof AppDailyTasksRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/my_profile': typeof AppMy_profileRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/stories': typeof AppStoriesRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/site/account': typeof SiteAccountRoute
  '/site/login': typeof SiteLoginRoute
  '/site/register': typeof SiteRegisterRoute
  '/app/': typeof AppIndexRoute
  '/api/public/giant-bot-webhook': typeof ApiPublicGiantBotWebhookRoute
  '/api/public/ota-publish': typeof ApiPublicOtaPublishRoute
  '/api/public/search-track': typeof ApiPublicSearchTrackRoute
  '/app/admin/community': typeof AppAdminCommunityRoute
  '/app/admin/rooms': typeof AppAdminRoomsRoute
  '/app/admin/stories': typeof AppAdminStoriesRoute
  '/app/admin/updates': typeof AppAdminUpdatesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/rooms/$id': typeof AppRoomsIdRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/chats/': typeof AppChatsIndexRoute
  '/app/rooms/$id/invites': typeof AppRoomsIdInvitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRouteWithChildren
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/app/account': typeof AppAccountRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/calls': typeof AppCallsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create-room': typeof AppCreateRoomRoute
  '/app/daily-tasks': typeof AppDailyTasksRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/my_profile': typeof AppMy_profileRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/stories': typeof AppStoriesRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/site/account': typeof SiteAccountRoute
  '/site/login': typeof SiteLoginRoute
  '/site/register': typeof SiteRegisterRoute
  '/app': typeof AppIndexRoute
  '/api/public/giant-bot-webhook': typeof ApiPublicGiantBotWebhookRoute
  '/api/public/ota-publish': typeof ApiPublicOtaPublishRoute
  '/api/public/search-track': typeof ApiPublicSearchTrackRoute
  '/app/admin/community': typeof AppAdminCommunityRoute
  '/app/admin/rooms': typeof AppAdminRoomsRoute
  '/app/admin/stories': typeof AppAdminStoriesRoute
  '/app/admin/updates': typeof AppAdminUpdatesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/rooms/$id': typeof AppRoomsIdRouteWithChildren
  '/app/admin': typeof AppAdminIndexRoute
  '/app/chats': typeof AppChatsIndexRoute
  '/app/rooms/$id/invites': typeof AppRoomsIdInvitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRouteWithChildren
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/recovery': typeof RecoveryRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/watch': typeof WatchRoute
  '/app/account': typeof AppAccountRoute
  '/app/achievements': typeof AppAchievementsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/calls': typeof AppCallsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/create-room': typeof AppCreateRoomRoute
  '/app/daily-tasks': typeof AppDailyTasksRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/my_profile': typeof AppMy_profileRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/stories': typeof AppStoriesRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/profile/$id': typeof ProfileIdRoute
  '/site/account': typeof SiteAccountRoute
  '/site/login': typeof SiteLoginRoute
  '/site/register': typeof SiteRegisterRoute
  '/app/': typeof AppIndexRoute
  '/api/public/giant-bot-webhook': typeof ApiPublicGiantBotWebhookRoute
  '/api/public/ota-publish': typeof ApiPublicOtaPublishRoute
  '/api/public/search-track': typeof ApiPublicSearchTrackRoute
  '/app/admin/community': typeof AppAdminCommunityRoute
  '/app/admin/rooms': typeof AppAdminRoomsRoute
  '/app/admin/stories': typeof AppAdminStoriesRoute
  '/app/admin/updates': typeof AppAdminUpdatesRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/profile/$id': typeof AppProfileIdRoute
  '/app/rooms/$id': typeof AppRoomsIdRouteWithChildren
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/chats/': typeof AppChatsIndexRoute
  '/app/rooms/$id/invites': typeof AppRoomsIdInvitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/features'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/recovery'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/site'
    | '/sitemap.xml'
    | '/terms'
    | '/watch'
    | '/app/account'
    | '/app/achievements'
    | '/app/activity'
    | '/app/admin'
    | '/app/calls'
    | '/app/community'
    | '/app/create-room'
    | '/app/daily-tasks'
    | '/app/friends'
    | '/app/games'
    | '/app/my_profile'
    | '/app/notifications'
    | '/app/settings'
    | '/app/store'
    | '/app/stories'
    | '/features/$slug'
    | '/profile/$id'
    | '/site/account'
    | '/site/login'
    | '/site/register'
    | '/app/'
    | '/api/public/giant-bot-webhook'
    | '/api/public/ota-publish'
    | '/api/public/search-track'
    | '/app/admin/community'
    | '/app/admin/rooms'
    | '/app/admin/stories'
    | '/app/admin/updates'
    | '/app/admin/users'
    | '/app/chats/$id'
    | '/app/profile/$id'
    | '/app/rooms/$id'
    | '/app/admin/'
    | '/app/chats/'
    | '/app/rooms/$id/invites'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/recovery'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/site'
    | '/sitemap.xml'
    | '/terms'
    | '/watch'
    | '/app/account'
    | '/app/achievements'
    | '/app/activity'
    | '/app/calls'
    | '/app/community'
    | '/app/create-room'
    | '/app/daily-tasks'
    | '/app/friends'
    | '/app/games'
    | '/app/my_profile'
    | '/app/notifications'
    | '/app/settings'
    | '/app/store'
    | '/app/stories'
    | '/features/$slug'
    | '/profile/$id'
    | '/site/account'
    | '/site/login'
    | '/site/register'
    | '/app'
    | '/api/public/giant-bot-webhook'
    | '/api/public/ota-publish'
    | '/api/public/search-track'
    | '/app/admin/community'
    | '/app/admin/rooms'
    | '/app/admin/stories'
    | '/app/admin/updates'
    | '/app/admin/users'
    | '/app/chats/$id'
    | '/app/profile/$id'
    | '/app/rooms/$id'
    | '/app/admin'
    | '/app/chats'
    | '/app/rooms/$id/invites'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/app'
    | '/features'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/recovery'
    | '/register'
    | '/reset-password'
    | '/reviews'
    | '/site'
    | '/sitemap.xml'
    | '/terms'
    | '/watch'
    | '/app/account'
    | '/app/achievements'
    | '/app/activity'
    | '/app/admin'
    | '/app/calls'
    | '/app/community'
    | '/app/create-room'
    | '/app/daily-tasks'
    | '/app/friends'
    | '/app/games'
    | '/app/my_profile'
    | '/app/notifications'
    | '/app/settings'
    | '/app/store'
    | '/app/stories'
    | '/features/$slug'
    | '/profile/$id'
    | '/site/account'
    | '/site/login'
    | '/site/register'
    | '/app/'
    | '/api/public/giant-bot-webhook'
    | '/api/public/ota-publish'
    | '/api/public/search-track'
    | '/app/admin/community'
    | '/app/admin/rooms'
    | '/app/admin/stories'
    | '/app/admin/updates'
    | '/app/admin/users'
    | '/app/chats/$id'
    | '/app/profile/$id'
    | '/app/rooms/$id'
    | '/app/admin/'
    | '/app/chats/'
    | '/app/rooms/$id/invites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRouteWithChildren
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoveryRoute: typeof RecoveryRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WatchRoute: typeof WatchRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ApiPublicGiantBotWebhookRoute: typeof ApiPublicGiantBotWebhookRoute
  ApiPublicOtaPublishRoute: typeof ApiPublicOtaPublishRoute
  ApiPublicSearchTrackRoute: typeof ApiPublicSearchTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/site/register': {
      id: '/site/register'
      path: '/register'
      fullPath: '/site/register'
      preLoaderRoute: typeof SiteRegisterRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/login': {
      id: '/site/login'
      path: '/login'
      fullPath: '/site/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/account': {
      id: '/site/account'
      path: '/account'
      fullPath: '/site/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/app/stories': {
      id: '/app/stories'
      path: '/stories'
      fullPath: '/app/stories'
      preLoaderRoute: typeof AppStoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my_profile': {
      id: '/app/my_profile'
      path: '/my_profile'
      fullPath: '/app/my_profile'
      preLoaderRoute: typeof AppMy_profileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games': {
      id: '/app/games'
      path: '/games'
      fullPath: '/app/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/daily-tasks': {
      id: '/app/daily-tasks'
      path: '/daily-tasks'
      fullPath: '/app/daily-tasks'
      preLoaderRoute: typeof AppDailyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create-room': {
      id: '/app/create-room'
      path: '/create-room'
      fullPath: '/app/create-room'
      preLoaderRoute: typeof AppCreateRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calls': {
      id: '/app/calls'
      path: '/calls'
      fullPath: '/app/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/': {
      id: '/app/chats/'
      path: '/chats'
      fullPath: '/app/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/rooms/$id': {
      id: '/app/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/app/rooms/$id'
      preLoaderRoute: typeof AppRoomsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/$id': {
      id: '/app/profile/$id'
      path: '/profile/$id'
      fullPath: '/app/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/$id': {
      id: '/app/chats/$id'
      path: '/chats/$id'
      fullPath: '/app/chats/$id'
      preLoaderRoute: typeof AppChatsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/updates': {
      id: '/app/admin/updates'
      path: '/updates'
      fullPath: '/app/admin/updates'
      preLoaderRoute: typeof AppAdminUpdatesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/stories': {
      id: '/app/admin/stories'
      path: '/stories'
      fullPath: '/app/admin/stories'
      preLoaderRoute: typeof AppAdminStoriesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/rooms': {
      id: '/app/admin/rooms'
      path: '/rooms'
      fullPath: '/app/admin/rooms'
      preLoaderRoute: typeof AppAdminRoomsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/community': {
      id: '/app/admin/community'
      path: '/community'
      fullPath: '/app/admin/community'
      preLoaderRoute: typeof AppAdminCommunityRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/search-track': {
      id: '/api/public/search-track'
      path: '/api/public/search-track'
      fullPath: '/api/public/search-track'
      preLoaderRoute: typeof ApiPublicSearchTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ota-publish': {
      id: '/api/public/ota-publish'
      path: '/api/public/ota-publish'
      fullPath: '/api/public/ota-publish'
      preLoaderRoute: typeof ApiPublicOtaPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/giant-bot-webhook': {
      id: '/api/public/giant-bot-webhook'
      path: '/api/public/giant-bot-webhook'
      fullPath: '/api/public/giant-bot-webhook'
      preLoaderRoute: typeof ApiPublicGiantBotWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rooms/$id/invites': {
      id: '/app/rooms/$id/invites'
      path: '/invites'
      fullPath: '/app/rooms/$id/invites'
      preLoaderRoute: typeof AppRoomsIdInvitesRouteImport
      parentRoute: typeof AppRoomsIdRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminCommunityRoute: typeof AppAdminCommunityRoute
  AppAdminRoomsRoute: typeof AppAdminRoomsRoute
  AppAdminStoriesRoute: typeof AppAdminStoriesRoute
  AppAdminUpdatesRoute: typeof AppAdminUpdatesRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminCommunityRoute: AppAdminCommunityRoute,
  AppAdminRoomsRoute: AppAdminRoomsRoute,
  AppAdminStoriesRoute: AppAdminStoriesRoute,
  AppAdminUpdatesRoute: AppAdminUpdatesRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRoomsIdRouteChildren {
  AppRoomsIdInvitesRoute: typeof AppRoomsIdInvitesRoute
}

const AppRoomsIdRouteChildren: AppRoomsIdRouteChildren = {
  AppRoomsIdInvitesRoute: AppRoomsIdInvitesRoute,
}

const AppRoomsIdRouteWithChildren = AppRoomsIdRoute._addFileChildren(
  AppRoomsIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCallsRoute: typeof AppCallsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppCreateRoomRoute: typeof AppCreateRoomRoute
  AppDailyTasksRoute: typeof AppDailyTasksRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppGamesRoute: typeof AppGamesRoute
  AppMy_profileRoute: typeof AppMy_profileRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoreRoute: typeof AppStoreRoute
  AppStoriesRoute: typeof AppStoriesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatsIdRoute: typeof AppChatsIdRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
  AppRoomsIdRoute: typeof AppRoomsIdRouteWithChildren
  AppChatsIndexRoute: typeof AppChatsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAchievementsRoute: AppAchievementsRoute,
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCallsRoute: AppCallsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppCreateRoomRoute: AppCreateRoomRoute,
  AppDailyTasksRoute: AppDailyTasksRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppGamesRoute: AppGamesRoute,
  AppMy_profileRoute: AppMy_profileRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoreRoute: AppStoreRoute,
  AppStoriesRoute: AppStoriesRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsIdRoute: AppChatsIdRoute,
  AppProfileIdRoute: AppProfileIdRoute,
  AppRoomsIdRoute: AppRoomsIdRouteWithChildren,
  AppChatsIndexRoute: AppChatsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FeaturesRouteChildren {
  FeaturesSlugRoute: typeof FeaturesSlugRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesSlugRoute: FeaturesSlugRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

interface SiteRouteChildren {
  SiteAccountRoute: typeof SiteAccountRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteRegisterRoute: typeof SiteRegisterRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAccountRoute: SiteAccountRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteRegisterRoute: SiteRegisterRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRouteWithChildren,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  RecoveryRoute: RecoveryRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WatchRoute: WatchRoute,
  ProfileIdRoute: ProfileIdRoute,
  ApiPublicGiantBotWebhookRoute: ApiPublicGiantBotWebhookRoute,
  ApiPublicOtaPublishRoute: ApiPublicOtaPublishRoute,
  ApiPublicSearchTrackRoute: ApiPublicSearchTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
