/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppStoreRouteImport } from './routes/app/store'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppNotificationsRouteImport } from './routes/app/notifications'
import { Route as AppGamesRouteImport } from './routes/app/games'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppChatsIndexRouteImport } from './routes/app/chats.index'
import { Route as AppRoomsIdRouteImport } from './routes/app/rooms.$id'
import { Route as AppChatsIdRouteImport } from './routes/app/chats.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoreRoute = AppStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesRoute = AppGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIndexRoute = AppChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsIdRoute = AppRoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppChatsIdRoute = AppChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/': typeof AppIndexRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/rooms/$id': typeof AppRoomsIdRoute
  '/app/chats/': typeof AppChatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app': typeof AppIndexRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/rooms/$id': typeof AppRoomsIdRoute
  '/app/chats': typeof AppChatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/admin': typeof AppAdminRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/games': typeof AppGamesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/store': typeof AppStoreRoute
  '/app/': typeof AppIndexRoute
  '/app/chats/$id': typeof AppChatsIdRoute
  '/app/rooms/$id': typeof AppRoomsIdRoute
  '/app/chats/': typeof AppChatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/friends'
    | '/app/games'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/store'
    | '/app/'
    | '/app/chats/$id'
    | '/app/rooms/$id'
    | '/app/chats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/friends'
    | '/app/games'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/store'
    | '/app'
    | '/app/chats/$id'
    | '/app/rooms/$id'
    | '/app/chats'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/admin'
    | '/app/friends'
    | '/app/games'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/store'
    | '/app/'
    | '/app/chats/$id'
    | '/app/rooms/$id'
    | '/app/chats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/store': {
      id: '/app/store'
      path: '/store'
      fullPath: '/app/store'
      preLoaderRoute: typeof AppStoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games': {
      id: '/app/games'
      path: '/games'
      fullPath: '/app/games'
      preLoaderRoute: typeof AppGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/': {
      id: '/app/chats/'
      path: '/chats'
      fullPath: '/app/chats/'
      preLoaderRoute: typeof AppChatsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rooms/$id': {
      id: '/app/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/app/rooms/$id'
      preLoaderRoute: typeof AppRoomsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chats/$id': {
      id: '/app/chats/$id'
      path: '/chats/$id'
      fullPath: '/app/chats/$id'
      preLoaderRoute: typeof AppChatsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppGamesRoute: typeof AppGamesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoreRoute: typeof AppStoreRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatsIdRoute: typeof AppChatsIdRoute
  AppRoomsIdRoute: typeof AppRoomsIdRoute
  AppChatsIndexRoute: typeof AppChatsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppGamesRoute: AppGamesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoreRoute: AppStoreRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatsIdRoute: AppChatsIdRoute,
  AppRoomsIdRoute: AppRoomsIdRoute,
  AppChatsIndexRoute: AppChatsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
